# Generated by Django 2.1.1 on 2018-09-12 21:01

from django.db import migrations, models
import pin_codes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=255, unique=True)),
                ('working_days', pin_codes.models.MultipleChoiceCharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=['0', '1', '2', '3', '4'])),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('start', 'end')},
        ),
        migrations.AddField(
            model_name='pincode',
            name='time_slots',
            field=models.ManyToManyField(to='pin_codes.TimeSlot'),
        ),
    ]
