# Generated by Django 2.1.1 on 2018-09-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliances', '0001_initial'),
        ('pin_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=4096)),
                ('place_id', models.CharField(blank=True, help_text='Google Maps Place ID', max_length=32, null=True)),
                ('weekday', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=8)),
                ('reason', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_number', models.CharField(max_length=255, unique=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=4096)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.Appliance')),
                ('pin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin_codes.PinCode')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin_codes.TimeSlot')),
            ],
        ),
    ]
